2018-07-13 10:24:24.289 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 10:26:46.854 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:34:39.750 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:35:16.702 [error] <0.224.0> gen_server <0.224.0> terminated with reason: socket_closed_unexpectedly
2018-07-13 10:35:16.702 [error] <0.224.0> CRASH REPORT Process <0.224.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/7 line 812
2018-07-13 10:35:16.702 [error] <0.222.0> Supervisor {<0.222.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.223.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.224.0> exit with reason socket_closed_unexpectedly in context child_terminated
2018-07-13 10:35:16.703 [error] <0.222.0> Supervisor {<0.222.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.223.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.224.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 10:35:24.549 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 10:52:57.160 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 10:52:57.242 [error] <0.225.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.ThrottleServ',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-07-13 10:52:57.242 [error] <0.223.0> CRASH REPORT Process <0.223.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ThrottleServ',{'EXIT',{undef,[{'Elixir.ThrottleServ',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{'Elixir.Throttling.Application',start,[normal,[amqp]]}} in application_master:init/4 line 134
2018-07-13 10:53:48.902 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 10:58:23.552 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 10:58:23.722 [error] <0.226.0> gen_server 'Elixir.ThrottleServ' terminated with reason: {'module could not be loaded',[{'Elixir.Channel',open,[#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.231.0>}],[]},{'Elixir.ThrottleServ',handle_info,2,[{file,"lib/throttling/throttle_serv.ex"},{line,32}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-07-13 10:58:23.722 [error] <0.226.0>@Elixir.Channel:open CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.231.0>}) in gen_server:terminate/7 line 812
2018-07-13 10:58:23.723 [error] <0.225.0>@Elixir.Channel:open Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.226.0> exit with reason call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.231.0>}) in context child_terminated
2018-07-13 10:58:23.724 [error] <0.245.0> gen_server 'Elixir.ThrottleServ' terminated with reason: {'module could not be loaded',[{'Elixir.Channel',open,[#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.248.0>}],[]},{'Elixir.ThrottleServ',handle_info,2,[{file,"lib/throttling/throttle_serv.ex"},{line,32}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-07-13 10:58:23.724 [error] <0.245.0>@Elixir.Channel:open CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.248.0>}) in gen_server:terminate/7 line 812
2018-07-13 10:58:23.724 [error] <0.225.0>@Elixir.Channel:open Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.245.0> exit with reason call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.248.0>}) in context child_terminated
2018-07-13 10:58:42.663 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:05:53.211 [error] <0.231.0> gen_server <0.231.0> terminated with reason: {socket_error,timeout}
2018-07-13 11:05:53.211 [error] <0.231.0> CRASH REPORT Process <0.231.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:terminate/7 line 812
2018-07-13 11:05:53.245 [error] <0.225.0> gen_server <0.225.0> terminated with reason: {socket_error,timeout}
2018-07-13 11:05:53.245 [error] <0.225.0> CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:terminate/7 line 812
2018-07-13 11:05:53.245 [error] <0.224.0> Supervisor {<0.224.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5935>, <0.225.0>, <0.229.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49963 -> 127.0.0.1:5672">>) at <0.231.0> exit with reason {socket_error,timeout} in context child_terminated
2018-07-13 11:05:53.245 [error] <0.224.0> Supervisor {<0.224.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5935>, <0.225.0>, <0.229.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49963 -> 127.0.0.1:5672">>) at <0.231.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:05:53.246 [error] <0.223.0> Supervisor {<0.223.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.224.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.225.0> exit with reason {socket_error,timeout} in context child_terminated
2018-07-13 11:05:53.246 [error] <0.223.0> Supervisor {<0.223.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.224.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.225.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:08:43.527 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:08:43.638 [error] <0.220.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.638 [error] <0.220.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.221.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.639 [error] <0.221.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.221.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.222.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.639 [error] <0.222.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.222.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.223.0> gen_server 'Elixir.ThrottleServ' terminated with reason: bad return value: nil
2018-07-13 11:08:43.639 [error] <0.223.0>@gen_server:terminate:812 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad return value: nil in gen_server:terminate/7 line 812
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.223.0> exit with reason bad return value: nil in context child_terminated
2018-07-13 11:08:43.639 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.223.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:53.859 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:09:54.002 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.002 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50118 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.002 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50118 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.002 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.008 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.008 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50119 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.008 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50119 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.008 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.016 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.016 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50120 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.016 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50120 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.016 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.024 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:09:54.025 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50121 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:09:54.025 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50121 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:09:54.025 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.276.0>},60000]}} in context child_terminated
2018-07-13 11:09:54.025 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:10:32.482 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:10:32.654 [error] <0.230.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.230.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:32.654 [error] <0.227.0> Supervisor {<0.227.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5603>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.229.0>, {<<"client 127.0.0.1:50134 -> 127.0.0.1:5672">>,1}) at <0.230.0> exit with reason badarg in context child_terminated
2018-07-13 11:10:32.654 [error] <0.227.0> Supervisor {<0.227.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5603>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.229.0>, {<<"client 127.0.0.1:50134 -> 127.0.0.1:5672">>,1}) at <0.230.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:10:32.654 [error] <0.208.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason {shutdown,{gen_server,call,[<0.229.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.209.0>},60000]}} in context child_terminated
2018-07-13 11:10:32.660 [error] <0.247.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.247.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:47.192 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:10:47.420 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:10:47.420 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50138 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:10:47.420 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50138 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:10:47.421 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:10:47.430 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:27.850 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:11:28.033 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.033 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50150 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.033 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50150 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.034 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.049 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.050 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50151 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.050 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6250>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50151 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.051 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.062 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.063 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50152 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.063 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6252>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50152 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.063 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.071 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:11:28.071 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50153 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:11:28.072 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6254>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50153 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:11:28.072 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.276.0>},60000]}} in context child_terminated
2018-07-13 11:11:28.072 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:12:02.412 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:12:02.622 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:12:02.622 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50157 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:12:02.623 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6018>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50157 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:12:02.623 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:12:02.632 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:12:25.176 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:13:09.596 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:13:09.809 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:13:09.810 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50175 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:13:09.810 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50175 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:13:09.810 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:13:09.819 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:15:43.644 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:15:43.892 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:15:43.892 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50207 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:15:43.892 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50207 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:15:43.893 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:15:43.903 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:16:56.308 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:16:56.541 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:16:56.541 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50238 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:16:56.541 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50238 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:16:56.541 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:16:56.551 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:04.805 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:05.034 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.034 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50242 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.035 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50242 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.035 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.047 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.047 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50243 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.047 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50243 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.048 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.056 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.056 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50244 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.057 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50244 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.057 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.066 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:05.066 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50245 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:05.066 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50245 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:05.066 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.277.0>},60000]}} in context child_terminated
2018-07-13 11:17:05.067 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:15.991 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:16.201 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.202 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50246 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.202 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6029>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50246 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.203 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.222 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.223 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50247 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.223 [error] <0.255.0> Supervisor {<0.255.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6261>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.257.0>, {<<"client 127.0.0.1:50247 -> 127.0.0.1:5672">>,1}) at <0.258.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.223 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason {shutdown,{gen_server,call,[<0.257.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.243.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.233 [error] <0.275.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.233 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50248 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.234 [error] <0.272.0> Supervisor {<0.272.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6263>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.274.0>, {<<"client 127.0.0.1:50248 -> 127.0.0.1:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.234 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason {shutdown,{gen_server,call,[<0.274.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.260.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.243 [error] <0.292.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.292.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:17:16.243 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50249 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason badarg in context child_terminated
2018-07-13 11:17:16.243 [error] <0.289.0> Supervisor {<0.289.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6265>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.291.0>, {<<"client 127.0.0.1:50249 -> 127.0.0.1:5672">>,1}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:16.244 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason {shutdown,{gen_server,call,[<0.291.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.276.0>},60000]}} in context child_terminated
2018-07-13 11:17:16.244 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:24.778 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:24.968 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:24.968 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:24.978 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:24.978 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:25.000 [error] <0.276.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:25.000 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:25.000 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.276.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:17:41.577 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:17:41.819 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:41.820 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:17:41.830 [error] <0.243.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:17:41.830 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:18:47.605 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:18:47.899 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:18:47.899 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:18:47.908 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:18:47.908 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:10.887 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:19:39.465 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:19:39.687 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:39.688 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:39.698 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:39.698 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:57.422 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:19:57.643 [error] <0.220.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:57.643 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:19:57.649 [error] <0.242.0> CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours crashed with reason: timeout_value in gen_server:loop/6 line 368
2018-07-13 11:19:57.649 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.242.0> exit with reason timeout_value in context child_terminated
2018-07-13 11:20:22.141 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:20:50.233 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:20:50.425 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:20:50.426 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50299 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:20:50.426 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6033>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50299 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:20:50.426 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:20:50.434 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:22:30.521 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:22:49.137 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:23:02.715 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:39:38.403 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:41:03.000 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:41:05.260 [error] <0.220.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:05.260 [error] <0.220.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:05.260 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:41:07.240 [error] <0.243.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.257.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:07.240 [error] <0.243.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.257.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:07.241 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.243.0> exit with reason no such process or port in call to gen_server:call(<0.257.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:41:09.250 [error] <0.260.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.274.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:09.250 [error] <0.260.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.274.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:09.250 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.260.0> exit with reason no such process or port in call to gen_server:call(<0.274.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:41:11.265 [error] <0.277.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.291.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:41:11.265 [error] <0.277.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.291.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:41:11.266 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason no such process or port in call to gen_server:call(<0.291.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:42:29.549 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:42:31.856 [error] <0.220.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:42:31.856 [error] <0.220.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:42:31.856 [error] <0.219.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason no such process or port in call to gen_server:call(<0.240.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:42:44.424 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:42:46.727 [error] <0.209.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:42:46.727 [error] <0.209.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:42:46.727 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:42:48.726 [error] <0.232.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:42:48.727 [error] <0.232.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:42:48.727 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.232.0> exit with reason no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:05.784 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:43:08.120 [error] <0.209.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:08.120 [error] <0.209.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:08.120 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason no such process or port in call to gen_server:call(<0.229.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:10.120 [error] <0.232.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:10.120 [error] <0.232.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:10.120 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.232.0> exit with reason no such process or port in call to gen_server:call(<0.246.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:12.129 [error] <0.249.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.263.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:12.129 [error] <0.249.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.263.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:12.129 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.249.0> exit with reason no such process or port in call to gen_server:call(<0.263.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:14.138 [error] <0.266.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.280.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:14.138 [error] <0.266.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.280.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:14.139 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.266.0> exit with reason no such process or port in call to gen_server:call(<0.280.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:16.147 [error] <0.283.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.297.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:16.147 [error] <0.283.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.297.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:16.148 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.283.0> exit with reason no such process or port in call to gen_server:call(<0.297.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:18.155 [error] <0.300.0>@gen_server:call gen_server 'Elixir.ThrottleServ' terminated with reason: no such process or port in call to gen_server:call(<0.314.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 212
2018-07-13 11:43:18.155 [error] <0.300.0>@gen_server:call CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.314.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:terminate/7 line 812
2018-07-13 11:43:18.155 [error] <0.208.0>@gen_server:call Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.300.0> exit with reason no such process or port in call to gen_server:call(<0.314.0>, {call,{'basic.publish',0,<<"my_exchange">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2018-07-13 11:43:53.232 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:43:53.528 [error] <0.241.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.241.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:43:53.528 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6022>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50598 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason badarg in context child_terminated
2018-07-13 11:43:53.529 [error] <0.238.0> Supervisor {<0.238.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6022>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.240.0>, {<<"client 127.0.0.1:50598 -> 127.0.0.1:5672">>,1}) at <0.241.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 11:43:53.529 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason {shutdown,{gen_server,call,[<0.240.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.220.0>},60000]}} in context child_terminated
2018-07-13 11:43:53.545 [error] <0.258.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.258.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-07-13 11:45:34.555 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:49:01.627 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 11:49:44.306 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:53:07.253 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 11:54:03.286 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 11:58:12.345 [error] <0.169.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.174.0> exit with reason normal in context child_terminated
2018-07-13 12:02:00.282 [error] <0.174.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.179.0> exit with reason normal in context child_terminated
2018-07-13 12:04:03.967 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:14:51.311 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:15:42.025 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:16:00.242 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 12:17:07.755 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:19:43.774 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.176.0> exit with reason normal in context child_terminated
2018-07-13 12:19:43.967 [error] <0.227.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:43.967 [error] <0.227.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:43.967 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.227.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:43.968 [error] <0.246.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:43.969 [error] <0.246.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:43.969 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.246.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:53.699 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.158.0> exit with reason normal in context child_terminated
2018-07-13 12:19:53.862 [error] <0.209.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:53.862 [error] <0.209.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:53.862 [error] <0.208.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.209.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:19:53.863 [error] <0.228.0>@Elixir.ThrottleServ:handle_info:33 gen_server 'Elixir.ThrottleServ' terminated with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33
2018-07-13 12:19:53.863 [error] <0.228.0>@Elixir.ThrottleServ:handle_info:33 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in gen_server:terminate/7 line 812
2018-07-13 12:19:53.863 [error] <0.208.0>@Elixir.ThrottleServ:handle_info:33 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.228.0> exit with reason no match of right hand value <<"Testing.db">> in 'Elixir.ThrottleServ':handle_info/2 line 33 in context child_terminated
2018-07-13 12:20:50.542 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:21:03.466 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:21:29.089 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:21:29.089 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:21:29.089 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:52 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52 in context child_terminated
2018-07-13 12:21:29.188 [error] <0.250.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.188 [error] <0.250.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.189 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.250.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:21:29.300 [error] <0.264.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.300 [error] <0.264.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.300 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.264.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:21:29.411 [error] <0.278.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.411 [error] <0.278.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:21:29.412 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.278.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:21:29.412 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.278.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 12:24:49.857 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.175.0> exit with reason normal in context child_terminated
2018-07-13 12:24:50.152 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:52 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:24:50.152 [error] <0.226.0>@Elixir.ThrottleServ:handle_info:52 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:24:50.152 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:52 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.226.0> exit with reason bad argument in call to queue:get([{queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}]) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52 in context child_terminated
2018-07-13 12:24:50.255 [error] <0.249.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.255 [error] <0.249.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.255 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.249.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:24:50.366 [error] <0.263.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.367 [error] <0.263.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.367 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.263.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:24:50.478 [error] <0.277.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.478 [error] <0.277.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:24:50.479 [error] <0.225.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:24:50.479 [error] <0.225.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.277.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 12:25:17.576 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:25:17.865 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to queue:get({queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:25:17.865 [error] <0.220.0>@Elixir.ThrottleServ:handle_info:52 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to queue:get({queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52
2018-07-13 12:25:17.866 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:52 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.220.0> exit with reason bad argument in call to queue:get({queue,{[<<"JqP5D5jXAEktbtEzEDsQAmkRFDTgujxjsFz44xRXwkpgjDV1X4nzGaTDR">>,<<"FKblWUzeDFw">>,<<"s">>,...],...}}) line 191 in 'Elixir.ThrottleServ':handle_info/2 line 52 in context child_terminated
2018-07-13 12:25:17.967 [error] <0.242.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:17.967 [error] <0.242.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.080 [error] <0.257.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.080 [error] <0.257.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.080 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.257.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:25:18.191 [error] <0.271.0>@Elixir.ThrottleServ:handle_info:45 gen_server 'Elixir.ThrottleServ' terminated with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.191 [error] <0.271.0>@Elixir.ThrottleServ:handle_info:45 CRASH REPORT Process 'Elixir.ThrottleServ' with 0 neighbours exited with reason: bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45
2018-07-13 12:25:18.191 [error] <0.219.0>@Elixir.ThrottleServ:handle_info:45 Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.271.0> exit with reason bad argument in call to dets:lookup(<<"Testing.db">>, queue) line 1267 in 'Elixir.ThrottleServ':handle_info/2 line 45 in context child_terminated
2018-07-13 12:25:18.192 [error] <0.219.0> Supervisor 'Elixir.Throttling.Supervisor' had child 'Elixir.ThrottleServ' started with 'Elixir.ThrottleServ':start_link() at <0.271.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-13 12:25:58.437 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:26:57.822 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:28:37.976 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
2018-07-13 12:29:20.454 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.169.0> exit with reason normal in context child_terminated
